### PR TITLE
community: switch meeting to 18:00 UTC

### PR DESCRIPTION
**Pull request by gotmax23**
Now that daylight savings/summer time has started, the meeting has moved back to 18:00 UTC.

### CODE REVIEW

**Comment by felixfontein** [comment]
In Europe, the DST switch only appens in a week. If the intention was to do this switch once the DST switch happened in Europe, this PR's a week too early. If the intention was to do it somewhen between the US DST switch and the European DST switch, then it's fine :)

**Review by Andersson007 — APPROVED** [review]
as am not regularly present, it's fine for me in any case:)

**Comment by gotmax23** [comment]
Let's wait until next week to change the meeting time.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Can I beg a review of the DaWGs PR for a similar update pls - https://github.com/ansible-community/meetings/pull/8 :-)

**Comment by mariolenz** [comment]
> Let's wait until next week to change the meeting time.

OK. but should `DTSTART` be changed to `20240403T180000Z` in this case? And `UID` maybe to `communityworkinggroup-20240403`?

**Comment by samccann** [comment]
From my perspective, it's not worth redoing the PR. It's kind of a pain to rerun the tool and then manually edit the resulting shared calendar to remove all those DSTART etc changes to the other two meetings in the list.

**Comment by mariolenz** [comment]
Apart from a question from me (which I consider answered by @samccann) we have two approvals and not one objection. Should we merge?

**Review by felixfontein — APPROVED** [review]
Let's merge (in particular since Europe also switched to summer time by now).

**Pull request merged**
